language: node_js
node_js:
- node
- '4.1'
- '4.0'
- '0.12'
- '0.11'
- iojs
env:
  matrix:
  - KARMA=yes MOCHA=no BUILD=no
  global:
  - secure: ZqysGmro+ElhUzZoeeYjrdK1EHR0FikyajTFxxH5L4BHs8/3XH5HOUwYYYimtisvINeeiu+uDRFRVZY8iuWSOCwcb7o32l8kP67K4bWTuibzZq+hwHNH9QdT81kgbUcwkqSLpAFnHo9u5zsHLCloQ76zQDpi7OkmYIf1hZLPHTaStIQwzg60T1m989fsdUoutvywH62g0jtEBhkZ8C+4DFe6eUYeys5e7McpTUmqCkJyAnp7g/VX7gVOnkr6tfpfOyw0fNICaS9XUOewH9d7MoQJoFyizT8xtjjK5oBDE+xjg3bSBTbZ9cUAj/UKRsSoc0YecX+IbGSTKtA+gvAV5fuejX0JPp4hi3thBGlA+fZJOjHlHgnqaTGEYS/D1iEZ8gHlcJFIAgAvyNDdK/wEjNYJ36gIsp5elvYRhUthj/8BzyClmoplIkgjgNo/mUZRGLuWQ9Ro5pyUIzcJkJqtVjxcNC+HYJ8sEv6Vc75kOpaYeXEedYsk6xelsoN0KVPZhBitqRRMsIQEZ3agttxt7zP6fBC/zw1sR3dBefeUfC/GPZOAeXMCxaZVThzhW21c2frz9nxwZnmUmOrHiuAWAN7AHw45AT3T5bsgJ+0BEDfPP3SkjdtgPvAWQakpJHDjCajLY1shHFuy/fYc3BizSXbctHzp9d+lbRENtYoE2wc=
matrix:
  include:
  - node_js: iojs
    env: KARMA=yes MOCHA=no BUILD=no
  - node_js: iojs
    env: KARMA=no MOCHA=yes BUILD=no
addons:
  sauce_connect:
    username: cundd
    access_key:
      secure: ZqysGmro+ElhUzZoeeYjrdK1EHR0FikyajTFxxH5L4BHs8/3XH5HOUwYYYimtisvINeeiu+uDRFRVZY8iuWSOCwcb7o32l8kP67K4bWTuibzZq+hwHNH9QdT81kgbUcwkqSLpAFnHo9u5zsHLCloQ76zQDpi7OkmYIf1hZLPHTaStIQwzg60T1m989fsdUoutvywH62g0jtEBhkZ8C+4DFe6eUYeys5e7McpTUmqCkJyAnp7g/VX7gVOnkr6tfpfOyw0fNICaS9XUOewH9d7MoQJoFyizT8xtjjK5oBDE+xjg3bSBTbZ9cUAj/UKRsSoc0YecX+IbGSTKtA+gvAV5fuejX0JPp4hi3thBGlA+fZJOjHlHgnqaTGEYS/D1iEZ8gHlcJFIAgAvyNDdK/wEjNYJ36gIsp5elvYRhUthj/8BzyClmoplIkgjgNo/mUZRGLuWQ9Ro5pyUIzcJkJqtVjxcNC+HYJ8sEv6Vc75kOpaYeXEedYsk6xelsoN0KVPZhBitqRRMsIQEZ3agttxt7zP6fBC/zw1sR3dBefeUfC/GPZOAeXMCxaZVThzhW21c2frz9nxwZnmUmOrHiuAWAN7AHw45AT3T5bsgJ+0BEDfPP3SkjdtgPvAWQakpJHDjCajLY1shHFuy/fYc3BizSXbctHzp9d+lbRENtYoE2wc=
sudo: false
before_script:
- npm install -g grunt-cli;
- npm install;
script:
- |
  if [[ "$BUILD" == "yes" ]]; then
    echo;
    echo "Build";
    grunt build;
  fi
- |
  if [[ "$KARMA" == "yes" ]]; then
    echo;
    echo "Running karma tests";
    grunt karma:ci;
  fi
- |-
  if [[ "$MOCHA" == "yes" ]]; then
    echo;
    grunt mochaTest;
  fi
